### ISSUE TITLE
Souci dans les spoilers - Markdown de Lien ne fonctionne pas

### ISSUE THREAD

**Issue by HeloiseLalande** [NeiagariCinematicUniverse/NcuWiki#1]
Lorsqu'on déploie les spoilers sur la page, les liens ne s'affichent pas. Par exemple sur le fichier markdown on a :

![Capture d’écran 2022-12-14 183550](https://user-images.githubusercontent.com/91457419/207667285-f6247cd0-3bda-4094-82e8-4507af8f8d6f.jpg)

Tandis que sur le rendu final on a :

![Capture d’écran 2022-12-14 183611](https://user-images.githubusercontent.com/91457419/207667349-ccffbecc-1783-4ebe-b024-e0b1e2735b7f.jpg)

**Comment by RedNeath** [comment]
Le problème était causé par la ligne
```javascript
spoiler.innerText = spoiler.innerText.substring(2);
```
lors de la génération des spoilers. Elle transformait le contenu HTML en contenu texte, ce qui avait pour effet d'annuler toutes les balises internes et de ne conserver que le texte.
Elle a été remplacée par 
```javascript
spoiler.innerHTML = spoiler.innerHTML.replace("<p>! ", "<p>");
```
qui conserve bel et bien toutes les propriétés HTML.
